### ISSUE TITLE
Missing Pages

### ISSUE THREAD

**Issue by Aevrin** [JeremyRuhland/webtoon-dl.py#5]
I tried downloading several items, and found that for longer items it was missing some of the earlier content. I don't know if there's a way to manually download these earlier pages or to bypass this limit.

**Comment by RaSan147** [comment]
> 
> 
> I tried downloading several items, and found that for longer items it was missing some of the earlier content. I don't know if there's a way to manually download these earlier pages or to bypass this limit.

can you please provide the links of the contents? things are a bit fuzzy

**Comment by Aevrin** [comment]
https://github.com/typingbeaver/webtoon-dl I think had a fix.
